"""create initial tables

Revision ID: 5472b1b9d375
Revises: 
Create Date: 2026-09-03 15:22:07.965192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5472b1b9d375'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grocery_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'COMPLETED', 'CANCELLED', name='grocery_session_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('package_size', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.Enum('USER_CONFIRMED', 'OCR_ASSISTED', 'EXTERNAL_DATABASE', 'ADMIN_CREATED', name='product_source_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)

    op.create_table('storage_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storage_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storage_locations_name'), ['name'], unique=True)

    op.create_table('inventory_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('storage_location_id', sa.Integer(), nullable=True),
    sa.Column('grocery_session_id', sa.Integer(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('original_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['grocery_session_id'], ['grocery_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_batches_expiration_date'), ['expiration_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_grocery_session_id'), ['grocery_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_remaining_quantity'), ['remaining_quantity'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_storage_location_id'), ['storage_location_id'], unique=False)

    op.create_table('shopping_list_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('is_bought', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shopping_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_list_items_is_bought'), ['is_bought'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopping_list_items_product_id'), ['product_id'], unique=False)

    op.create_table('inventory_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('PURCHASED', 'CONSUMED', 'DISCARDED', 'EXPIRED', 'ADJUSTMENT', 'TRANSFERRED', name='event_type_enum'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_events_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_events_occurred_at'), ['occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_inventory_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_inventory_events_batch_id'))

    op.drop_table('inventory_events')
    with op.batch_alter_table('shopping_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopping_list_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_shopping_list_items_is_bought'))

    op.drop_table('shopping_list_items')
    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_batches_storage_location_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_remaining_quantity'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_grocery_session_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_expiration_date'))

    op.drop_table('inventory_batches')
    with op.batch_alter_table('storage_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storage_locations_name'))

    op.drop_table('storage_locations')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_category'))
        batch_op.drop_index(batch_op.f('ix_products_barcode'))

    op.drop_table('products')
    op.drop_table('grocery_sessions')
    # ### end Alembic commands ###
